server:
  port: 9091
spring:
  application:
    name: productrocketmq


eureka:
 client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/


#http://blog.csdn.net/qq_22841811/article/details/67783473
rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: jack
    #mq的nameserver地址,多个分号隔开
    namesrvAddr: localhost:9876
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: jackProduct
    #topic名称
    topic: TEST
    #根据实际情况设置消息的tag
    tag: TEST
    #消息最大长度
    maxMessageSize: 131072 # 1024*128
    #发送消息超时时间
    sendMsgTimeout: 10000
  consumer:
    namesrvAddr: localhost:9876
    groupName: jack
    topic: sms
    tag: verifycode
    consumeThreadMin: 20
    consumeThreadMax: 64






