server:
  port: 9090
spring:
  application:
    name: spring-cloud-consumer
  datasource:
    name: jack1
    url: jdbc:mysql://localhost:3306/jack?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    #druid数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #mapper-locations: classpath:com/jack/mapper/**/*.xml
  typeAliasesPackage: com.jack.entity
##global-config:
#主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  global-config:
    id-type: 2
#字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
#驼峰下划线转换
    db-column-underline: true
#刷新mapper 调试神器
    refresh-mapper: true
#数据库大写下划线转换
#capital-mode: true
#序列接口实现类配置
#key-generator: com.baomidou.springboot.xxx
#逻辑删除配置
#logic-delete-value: 0
#logic-not-delete-value: 1
#自定义填充策略接口实现
#meta-object-handler: com.baomidou.springboot.xxx
#自定义SQL注入器
#sql-injector: com.baomidou.springboot.xxx
##configuration:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level: warn

test:
  name: jack
  age: 22
  address: 深圳

